/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Masajista;
import persistencia.ClienteData;
import persistencia.Conexion;

/**
 *
 * @author Maxi
 */
public class ClienteRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public ClienteRegistro() {
        initComponents();
    }

    
    Conexion con = new Conexion();
     ClienteData operacionesCliente = new ClienteData(con);
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_codCli = new javax.swing.JLabel();
        jl_dni = new javax.swing.JLabel();
        jl_nombreCompleto = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_edad = new javax.swing.JLabel();
        jl_afecciones = new javax.swing.JLabel();
        jl_estado = new javax.swing.JLabel();
        txt_codCli = new java.awt.TextField();
        txt_nombreCompleto = new java.awt.TextField();
        txt_documento = new java.awt.TextField();
        txt_telefono = new java.awt.TextField();
        txt_edad = new java.awt.TextField();
        txt_afecciones = new java.awt.TextField();
        btn_bajaLogica = new java.awt.Button();
        btn_altaLogica = new java.awt.Button();
        jb_notaCodCli = new javax.swing.JLabel();
        jb_notaCodCli1 = new javax.swing.JLabel();
        ck_clienteActivo = new javax.swing.JCheckBox();
        btn_buscarCli = new javax.swing.JButton();
        btn_regisCli = new javax.swing.JButton();
        btn_actuCli = new javax.swing.JButton();
        btn_borrarCli = new javax.swing.JButton();
        btn_limpiarCli = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jl_codCli.setBackground(new java.awt.Color(255, 255, 255));
        jl_codCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_codCli.setForeground(new java.awt.Color(0, 0, 0));
        jl_codCli.setText("Codigo Cliente");

        jl_dni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_dni.setForeground(new java.awt.Color(0, 0, 0));
        jl_dni.setText("Documento");

        jl_nombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_nombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        jl_nombreCompleto.setText("Nombre y Apellido");

        jl_telefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_telefono.setForeground(new java.awt.Color(0, 0, 0));
        jl_telefono.setText("Telefono");

        jl_edad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_edad.setForeground(new java.awt.Color(0, 0, 0));
        jl_edad.setText("Edad");

        jl_afecciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_afecciones.setForeground(new java.awt.Color(0, 0, 0));
        jl_afecciones.setText("Afecciones");

        jl_estado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_estado.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado.setText("Activo");

        txt_codCli.setBackground(new java.awt.Color(153, 255, 255));
        txt_codCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_codCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codCliActionPerformed(evt);
            }
        });

        txt_nombreCompleto.setBackground(new java.awt.Color(153, 255, 255));
        txt_nombreCompleto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_nombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreCompletoActionPerformed(evt);
            }
        });

        txt_documento.setBackground(new java.awt.Color(153, 255, 255));
        txt_documento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_documentoActionPerformed(evt);
            }
        });

        txt_telefono.setBackground(new java.awt.Color(153, 255, 255));
        txt_telefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        txt_edad.setBackground(new java.awt.Color(153, 255, 255));
        txt_edad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });

        txt_afecciones.setBackground(new java.awt.Color(153, 255, 255));
        txt_afecciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_afecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_afeccionesActionPerformed(evt);
            }
        });

        btn_bajaLogica.setBackground(new java.awt.Color(153, 255, 255));
        btn_bajaLogica.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        btn_bajaLogica.setLabel("Baja");
        btn_bajaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bajaLogicaActionPerformed(evt);
            }
        });

        btn_altaLogica.setBackground(new java.awt.Color(153, 255, 255));
        btn_altaLogica.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        btn_altaLogica.setLabel("Alta");
        btn_altaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaLogicaActionPerformed(evt);
            }
        });

        jb_notaCodCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_notaCodCli.setForeground(new java.awt.Color(0, 0, 0));
        jb_notaCodCli.setText("*Para registrarse este campo debe estar vacio");

        jb_notaCodCli1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jb_notaCodCli1.setForeground(new java.awt.Color(0, 0, 0));
        jb_notaCodCli1.setText("SPA ENTRE DEDOS                                   CLIENTES");

        ck_clienteActivo.setBackground(new java.awt.Color(255, 255, 255));
        ck_clienteActivo.setForeground(new java.awt.Color(0, 153, 255));

        btn_buscarCli.setBackground(new java.awt.Color(0, 204, 204));
        btn_buscarCli.setForeground(new java.awt.Color(0, 0, 0));
        btn_buscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda_1.png"))); // NOI18N
        btn_buscarCli.setText("Buscar");
        btn_buscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCliActionPerformed(evt);
            }
        });

        btn_regisCli.setBackground(new java.awt.Color(0, 204, 204));
        btn_regisCli.setForeground(new java.awt.Color(0, 0, 0));
        btn_regisCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        btn_regisCli.setText("Registrar");
        btn_regisCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regisCliActionPerformed(evt);
            }
        });

        btn_actuCli.setBackground(new java.awt.Color(0, 204, 204));
        btn_actuCli.setForeground(new java.awt.Color(0, 0, 0));
        btn_actuCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-actualizar-50.png"))); // NOI18N
        btn_actuCli.setText("Actualizar");
        btn_actuCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actuCliActionPerformed(evt);
            }
        });

        btn_borrarCli.setBackground(new java.awt.Color(0, 204, 204));
        btn_borrarCli.setForeground(new java.awt.Color(0, 0, 0));
        btn_borrarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btn_borrarCli.setText("Borrar registro");
        btn_borrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarCliActionPerformed(evt);
            }
        });

        btn_limpiarCli.setBackground(new java.awt.Color(0, 204, 204));
        btn_limpiarCli.setForeground(new java.awt.Color(0, 0, 0));
        btn_limpiarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-escoba-50.png"))); // NOI18N
        btn_limpiarCli.setText("Limpiar campos");
        btn_limpiarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_bajaLogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_altaLogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jl_estado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ck_clienteActivo))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jl_edad)
                                            .addComponent(jl_codCli)
                                            .addComponent(jl_dni)
                                            .addComponent(jl_telefono))))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_afecciones, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_nombreCompleto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_afecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_notaCodCli)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_codCli, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_buscarCli)
                                    .addComponent(btn_limpiarCli)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn_actuCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_regisCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btn_borrarCli)))))
                    .addComponent(jb_notaCodCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_notaCodCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jb_notaCodCli)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl_dni))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buscarCli)
                            .addComponent(jl_codCli)
                            .addComponent(txt_codCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_nombreCompleto)
                            .addComponent(txt_nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_regisCli))
                .addGap(9, 9, 9)
                .addComponent(btn_actuCli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_telefono)
                    .addComponent(btn_borrarCli))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_edad)
                            .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiarCli)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_afecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_afecciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_altaLogica, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_bajaLogica, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_estado)
                                    .addComponent(ck_clienteActivo))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codCliActionPerformed

    private void txt_nombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCompletoActionPerformed

    private void txt_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documentoActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_afeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_afeccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_afeccionesActionPerformed

    private void btn_bajaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bajaLogicaActionPerformed
        
        try {
            
        
        int seleccionCodigoCliente = Integer.parseInt(txt_codCli.getText());
        String seleccionDocumento = txt_documento.getText();
        String seleccionNombreCompleto = txt_nombreCompleto.getText();
        String seleccionTelefono = txt_telefono.getText();
        String seleccionEdad = txt_edad.getText();
        String seleccionAfecciones = txt_afecciones.getText();
        boolean seleccionEstado = ck_clienteActivo.isSelected();
        
        Cliente clienteCreado = new Cliente(seleccionCodigoCliente, Integer.parseInt(seleccionDocumento), seleccionNombreCompleto, Long.valueOf(seleccionTelefono), Integer.parseInt(seleccionEdad), seleccionAfecciones, seleccionEstado);
        operacionesCliente.bajaLogica(clienteCreado);
        JOptionPane.showMessageDialog(this, "Cliente dado de baja correctamente");
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar un cliente valido", "Faltan datos del cliente", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
    }//GEN-LAST:event_btn_bajaLogicaActionPerformed

    private void btn_altaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaLogicaActionPerformed
        
    try{
        int seleccionCodigoCliente = Integer.parseInt(txt_codCli.getText());
        String seleccionDocumento = txt_documento.getText();
        String seleccionNombreCompleto = txt_nombreCompleto.getText();
        String seleccionTelefono = txt_telefono.getText();
        String seleccionEdad = txt_edad.getText();
        String seleccionAfecciones = txt_afecciones.getText();
        boolean seleccionEstado = ck_clienteActivo.isSelected();
        
        Cliente clienteCreado = new Cliente(seleccionCodigoCliente, Integer.parseInt(seleccionDocumento), seleccionNombreCompleto, Long.valueOf(seleccionTelefono), Integer.parseInt(seleccionEdad), seleccionAfecciones, seleccionEstado);
        operacionesCliente.altaLogica(clienteCreado);
        JOptionPane.showMessageDialog(this, "Cliente dado de alta correctamente");
        
    } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar un cliente valido", "Faltan datos del cliente", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
    }//GEN-LAST:event_btn_altaLogicaActionPerformed

    private void btn_buscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCliActionPerformed
       try {
        
        int seleccion = Integer.parseInt(txt_codCli.getText().trim());
        txt_codCli.setText(String.valueOf(operacionesCliente.buscarCliente(seleccion).getCodCli()));
        txt_documento.setText(String.valueOf(operacionesCliente.buscarCliente(seleccion).getDni()));
        txt_nombreCompleto.setText(String.valueOf(operacionesCliente.buscarCliente(seleccion).getNombreCompleto()));
        txt_telefono.setText(String.valueOf(operacionesCliente.buscarCliente(seleccion).getTelefono()));
        txt_edad.setText(String.valueOf(operacionesCliente.buscarCliente(seleccion).getEdad()));
        txt_afecciones.setText(operacionesCliente.buscarCliente(seleccion).getAfecciones());
        ck_clienteActivo.setSelected(operacionesCliente.buscarCliente(seleccion).isEstado());
        
       } catch (NumberFormatException e) {
           
           JOptionPane.showMessageDialog(this, "El codigo de cliente tiene que ser un numero", "Error codigo cliente", JOptionPane.ERROR_MESSAGE);
           
       }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarCliActionPerformed

    private void btn_regisCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regisCliActionPerformed
        
       try{ 
        String seleccionDocumento = txt_documento.getText();
        String seleccionNombreCompleto = txt_nombreCompleto.getText();
        String seleccionTelefono = txt_telefono.getText();
        String seleccionEdad = txt_edad.getText();
        String seleccionAfecciones = txt_afecciones.getText();
        boolean seleccionEstado = ck_clienteActivo.isSelected();
        
        Cliente clienteCreado = new Cliente(Integer.parseInt(seleccionDocumento), seleccionNombreCompleto, Long.valueOf(seleccionTelefono), Integer.parseInt(seleccionEdad), seleccionAfecciones, seleccionEstado);
        operacionesCliente.agregarCliente(clienteCreado);
        JOptionPane.showMessageDialog(this, "Se agrego el cliente: " + seleccionNombreCompleto + " correctamente");
        
       } catch (NumberFormatException e) {
           
          JOptionPane.showMessageDialog(this,  "Error:Documento, telefono y edad tienen que ser numeros validos", "Error de campos",  JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btn_regisCliActionPerformed

    private void btn_actuCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actuCliActionPerformed
       try {
        
        int seleccionCodigoCliente = Integer.parseInt(txt_codCli.getText());
        String seleccionDocumento = txt_documento.getText();
        String seleccionNombreCompleto = txt_nombreCompleto.getText();
        String seleccionTelefono = txt_telefono.getText();
        String seleccionEdad = txt_edad.getText();
        String seleccionAfecciones = txt_afecciones.getText();
        boolean seleccionEstado = ck_clienteActivo.isSelected();
        
        Cliente clienteActualizado = new Cliente(seleccionCodigoCliente, Integer.parseInt(seleccionDocumento), seleccionNombreCompleto, Long.valueOf(seleccionTelefono), Integer.parseInt(seleccionEdad), seleccionAfecciones, seleccionEstado);
        operacionesCliente.actualizarCliente(clienteActualizado);
        JOptionPane.showMessageDialog(this, "Se actualizo el cliente: " + seleccionNombreCompleto + " correctamente");
        
        } catch (NumberFormatException e) {
           
           JOptionPane.showMessageDialog(this, "Error: Documento, telefono y edad tienen que ser numeros validos", "Error en campos", JOptionPane.ERROR_MESSAGE);
           
       }    
    }//GEN-LAST:event_btn_actuCliActionPerformed

    private void btn_borrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarCliActionPerformed
    try{
        int seleccionCodigoCliente = Integer.parseInt(txt_codCli.getText());
        
        operacionesCliente.eliminarCliente(seleccionCodigoCliente);
        JOptionPane.showMessageDialog(this, "Cliente borrado actualmente"); 
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar un codigo de cliente valido", "Codigo de cliente incorrecto", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btn_borrarCliActionPerformed

    private void btn_limpiarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCliActionPerformed
           txt_codCli.setText("");
        txt_documento.setText("");      
        txt_nombreCompleto.setText("");
        txt_telefono.setText("");
        txt_edad.setText("");  
        txt_afecciones.setText("");
        ck_clienteActivo.setSelected(false);
        
                
                
        
    }//GEN-LAST:event_btn_limpiarCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actuCli;
    private java.awt.Button btn_altaLogica;
    private java.awt.Button btn_bajaLogica;
    private javax.swing.JButton btn_borrarCli;
    private javax.swing.JButton btn_buscarCli;
    private javax.swing.JButton btn_limpiarCli;
    private javax.swing.JButton btn_regisCli;
    private javax.swing.JCheckBox ck_clienteActivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jb_notaCodCli;
    private javax.swing.JLabel jb_notaCodCli1;
    private javax.swing.JLabel jl_afecciones;
    private javax.swing.JLabel jl_codCli;
    private javax.swing.JLabel jl_dni;
    private javax.swing.JLabel jl_edad;
    private javax.swing.JLabel jl_estado;
    private javax.swing.JLabel jl_nombreCompleto;
    private javax.swing.JLabel jl_telefono;
    private java.awt.TextField txt_afecciones;
    private java.awt.TextField txt_codCli;
    private java.awt.TextField txt_documento;
    private java.awt.TextField txt_edad;
    private java.awt.TextField txt_nombreCompleto;
    private java.awt.TextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
