/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Maxi
 */
public class JF_inicio extends javax.swing.JFrame {

    /**
     * Creates new form JF_inicio
     */
    public JF_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktp_principal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCliente = new javax.swing.JMenu();
        jmitem_Cliente = new javax.swing.JMenuItem();
        jmMasajistas = new javax.swing.JMenu();
        jmitem_MasajistaList = new javax.swing.JMenuItem();
        jmitem_MasajistaContrato = new javax.swing.JMenuItem();
        jmInstalaciones = new javax.swing.JMenu();
        jmitem_InstalacionesList = new javax.swing.JMenuItem();
        jmTratamiento = new javax.swing.JMenu();
        jmitem_TratamientoList = new javax.swing.JMenuItem();
        jmitem_TratamientoRegistro = new javax.swing.JMenuItem();
        jmReserva = new javax.swing.JMenu();
        jmitem_reservaTratamiento = new javax.swing.JMenuItem();
        jmitem_reservaIntalaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dsktp_principalLayout = new javax.swing.GroupLayout(dsktp_principal);
        dsktp_principal.setLayout(dsktp_principalLayout);
        dsktp_principalLayout.setHorizontalGroup(
            dsktp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1285, Short.MAX_VALUE)
        );
        dsktp_principalLayout.setVerticalGroup(
            dsktp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jmCliente.setText("Cliente");

        jmitem_Cliente.setText("Registro");
        jmitem_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_ClienteMouseClicked(evt);
            }
        });
        jmitem_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_ClienteActionPerformed(evt);
            }
        });
        jmCliente.add(jmitem_Cliente);

        jMenuBar1.add(jmCliente);

        jmMasajistas.setText("Masajistas");

        jmitem_MasajistaList.setText("Listado");
        jmitem_MasajistaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_MasajistaListMouseClicked(evt);
            }
        });
        jmitem_MasajistaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_MasajistaListActionPerformed(evt);
            }
        });
        jmMasajistas.add(jmitem_MasajistaList);

        jmitem_MasajistaContrato.setText("Contratar");
        jmitem_MasajistaContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_MasajistaContratoMouseClicked(evt);
            }
        });
        jmitem_MasajistaContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_MasajistaContratoActionPerformed(evt);
            }
        });
        jmMasajistas.add(jmitem_MasajistaContrato);

        jMenuBar1.add(jmMasajistas);

        jmInstalaciones.setText("Intalaciones");

        jmitem_InstalacionesList.setText("Listado ");
        jmitem_InstalacionesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_InstalacionesListActionPerformed(evt);
            }
        });
        jmInstalaciones.add(jmitem_InstalacionesList);

        jMenuBar1.add(jmInstalaciones);

        jmTratamiento.setText("Tratamientos");

        jmitem_TratamientoList.setText("Listado");
        jmitem_TratamientoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_TratamientoListMouseClicked(evt);
            }
        });
        jmitem_TratamientoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_TratamientoListActionPerformed(evt);
            }
        });
        jmTratamiento.add(jmitem_TratamientoList);

        jmitem_TratamientoRegistro.setText("Registro ");
        jmitem_TratamientoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_TratamientoRegistroMouseClicked(evt);
            }
        });
        jmitem_TratamientoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_TratamientoRegistroActionPerformed(evt);
            }
        });
        jmTratamiento.add(jmitem_TratamientoRegistro);

        jMenuBar1.add(jmTratamiento);

        jmReserva.setText("Reservas");

        jmitem_reservaTratamiento.setText("reserva tratamiento");
        jmitem_reservaTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_reservaTratamientoActionPerformed(evt);
            }
        });
        jmReserva.add(jmitem_reservaTratamiento);

        jmitem_reservaIntalaciones.setText("reserva instalacion");
        jmitem_reservaIntalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_reservaIntalacionesActionPerformed(evt);
            }
        });
        jmReserva.add(jmitem_reservaIntalaciones);

        jMenuBar1.add(jmReserva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktp_principal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmitem_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_ClienteMouseClicked

        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ClienteRegistro vistaRegistroCliente = new ClienteRegistro();
        vistaRegistroCliente.setVisible(true);
        dsktp_principal.add(vistaRegistroCliente);
        dsktp_principal.moveToFront(vistaRegistroCliente);


    }//GEN-LAST:event_jmitem_ClienteMouseClicked

    private void jmitem_MasajistaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_MasajistaListMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoMasajista listadoMasajistas = new ListadoMasajista();
        listadoMasajistas.setVisible(true);
        dsktp_principal.add(listadoMasajistas);
        dsktp_principal.moveToFront(listadoMasajistas);
    }//GEN-LAST:event_jmitem_MasajistaListMouseClicked

    private void jmitem_MasajistaContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_MasajistaContratoMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ContratoMasajista contratoMasajista = new ContratoMasajista();
        contratoMasajista.setVisible(true);
        dsktp_principal.add(contratoMasajista);
        dsktp_principal.moveToFront(contratoMasajista);
    }//GEN-LAST:event_jmitem_MasajistaContratoMouseClicked

    private void jmitem_TratamientoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_TratamientoListMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoTratamientos listadoTratamientos = new ListadoTratamientos();
        listadoTratamientos.setVisible(true);
        dsktp_principal.add(listadoTratamientos);
        dsktp_principal.moveToFront(listadoTratamientos);
    }//GEN-LAST:event_jmitem_TratamientoListMouseClicked

    private void jmitem_TratamientoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_TratamientoRegistroMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        RegistroTratamiento registoTratamiento = new RegistroTratamiento();
        registoTratamiento.setVisible(true);
        dsktp_principal.add(registoTratamiento);
        dsktp_principal.moveToFront(registoTratamiento);
    }//GEN-LAST:event_jmitem_TratamientoRegistroMouseClicked

    private void jmitem_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_ClienteActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ClienteRegistro vistaRegistroCliente = new ClienteRegistro();
        vistaRegistroCliente.setVisible(true);
        dsktp_principal.add(vistaRegistroCliente);
        dsktp_principal.moveToFront(vistaRegistroCliente);
    }//GEN-LAST:event_jmitem_ClienteActionPerformed

    private void jmitem_MasajistaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_MasajistaListActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoMasajista listadoMasajistas = new ListadoMasajista();
        listadoMasajistas.setVisible(true);
        dsktp_principal.add(listadoMasajistas);
        dsktp_principal.moveToFront(listadoMasajistas);
    }//GEN-LAST:event_jmitem_MasajistaListActionPerformed

    private void jmitem_MasajistaContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_MasajistaContratoActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ContratoMasajista contratoMasajista = new ContratoMasajista();
        contratoMasajista.setVisible(true);
        dsktp_principal.add(contratoMasajista);
        dsktp_principal.moveToFront(contratoMasajista);
    }//GEN-LAST:event_jmitem_MasajistaContratoActionPerformed

    private void jmitem_InstalacionesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_InstalacionesListActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoInstalaciones listadoInstalaciones = new ListadoInstalaciones();
        listadoInstalaciones.setVisible(true);
        dsktp_principal.add(listadoInstalaciones);
        dsktp_principal.moveToFront(listadoInstalaciones);
    }//GEN-LAST:event_jmitem_InstalacionesListActionPerformed

    private void jmitem_TratamientoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_TratamientoListActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoTratamientos listadoTratamientos = new ListadoTratamientos();
        listadoTratamientos.setVisible(true);
        dsktp_principal.add(listadoTratamientos);
        dsktp_principal.moveToFront(listadoTratamientos);
    }//GEN-LAST:event_jmitem_TratamientoListActionPerformed

    private void jmitem_TratamientoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_TratamientoRegistroActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        RegistroTratamiento registoTratamiento = new RegistroTratamiento();
        registoTratamiento.setVisible(true);
        dsktp_principal.add(registoTratamiento);
        dsktp_principal.moveToFront(registoTratamiento);
    }//GEN-LAST:event_jmitem_TratamientoRegistroActionPerformed

    private void jmitem_reservaTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_reservaTratamientoActionPerformed
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        Sesiones vistaSesiones = new Sesiones();
        vistaSesiones.setVisible(true);
        dsktp_principal.add(vistaSesiones);
        dsktp_principal.moveToFront(vistaSesiones);
    }//GEN-LAST:event_jmitem_reservaTratamientoActionPerformed

    private void jmitem_reservaIntalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_reservaIntalacionesActionPerformed
        
    }//GEN-LAST:event_jmitem_reservaIntalacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktp_principal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenu jmInstalaciones;
    private javax.swing.JMenu jmMasajistas;
    private javax.swing.JMenu jmReserva;
    private javax.swing.JMenu jmTratamiento;
    private javax.swing.JMenuItem jmitem_Cliente;
    private javax.swing.JMenuItem jmitem_InstalacionesList;
    private javax.swing.JMenuItem jmitem_MasajistaContrato;
    private javax.swing.JMenuItem jmitem_MasajistaList;
    private javax.swing.JMenuItem jmitem_TratamientoList;
    private javax.swing.JMenuItem jmitem_TratamientoRegistro;
    private javax.swing.JMenuItem jmitem_reservaIntalaciones;
    private javax.swing.JMenuItem jmitem_reservaTratamiento;
    // End of variables declaration//GEN-END:variables
}
