/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Maxi
 */
public class JF_inicio extends javax.swing.JFrame {

    /**
     * Creates new form JF_inicio
     */
    public JF_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktp_principal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCliente = new javax.swing.JMenu();
        jmitem_Cliente = new javax.swing.JMenuItem();
        jmMasajistas = new javax.swing.JMenu();
        jmitem_MasajistaList = new javax.swing.JMenuItem();
        jmitem_MasajistaContrato = new javax.swing.JMenuItem();
        jmInstalaciones = new javax.swing.JMenu();
        jmitem_InstalacionesList = new javax.swing.JMenuItem();
        jmTratamiento = new javax.swing.JMenu();
        jmitem_TratamientoList = new javax.swing.JMenuItem();
        jmitem_TratamientoRegistro = new javax.swing.JMenuItem();
        jmSesiones = new javax.swing.JMenu();
        jmitem_SesionNueva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dsktp_principalLayout = new javax.swing.GroupLayout(dsktp_principal);
        dsktp_principal.setLayout(dsktp_principalLayout);
        dsktp_principalLayout.setHorizontalGroup(
            dsktp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        dsktp_principalLayout.setVerticalGroup(
            dsktp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jmCliente.setText("Cliente");

        jmitem_Cliente.setText("Registro");
        jmitem_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_ClienteMouseClicked(evt);
            }
        });
        jmCliente.add(jmitem_Cliente);

        jMenuBar1.add(jmCliente);

        jmMasajistas.setText("Masajistas");

        jmitem_MasajistaList.setText("Listado");
        jmitem_MasajistaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_MasajistaListMouseClicked(evt);
            }
        });
        jmMasajistas.add(jmitem_MasajistaList);

        jmitem_MasajistaContrato.setText("Contratar");
        jmitem_MasajistaContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_MasajistaContratoMouseClicked(evt);
            }
        });
        jmMasajistas.add(jmitem_MasajistaContrato);

        jMenuBar1.add(jmMasajistas);

        jmInstalaciones.setText("Intalaciones");

        jmitem_InstalacionesList.setText("Listado ");
        jmInstalaciones.add(jmitem_InstalacionesList);

        jMenuBar1.add(jmInstalaciones);

        jmTratamiento.setText("Tratamientos");

        jmitem_TratamientoList.setText("Listado");
        jmitem_TratamientoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_TratamientoListMouseClicked(evt);
            }
        });
        jmTratamiento.add(jmitem_TratamientoList);

        jmitem_TratamientoRegistro.setText("Registro ");
        jmitem_TratamientoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitem_TratamientoRegistroMouseClicked(evt);
            }
        });
        jmTratamiento.add(jmitem_TratamientoRegistro);

        jMenuBar1.add(jmTratamiento);

        jmSesiones.setText("Sesiones");

        jmitem_SesionNueva.setText("Sacar Turno");
        jmSesiones.add(jmitem_SesionNueva);

        jMenuBar1.add(jmSesiones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktp_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitem_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_ClienteMouseClicked
        
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ClienteRegistro vistaRegistroCliente = new ClienteRegistro();
        vistaRegistroCliente.setVisible(true);
        dsktp_principal.add(vistaRegistroCliente);
        dsktp_principal.moveToFront(vistaRegistroCliente);
        
        
        
        
        
    }//GEN-LAST:event_jmitem_ClienteMouseClicked

    private void jmitem_MasajistaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_MasajistaListMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoMasajista listadoMasajistas = new ListadoMasajista();
        listadoMasajistas.setVisible(true);
        dsktp_principal.add(listadoMasajistas);
        dsktp_principal.moveToFront(listadoMasajistas);
    }//GEN-LAST:event_jmitem_MasajistaListMouseClicked

    private void jmitem_MasajistaContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_MasajistaContratoMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ContratoMasajista contratoMasajista = new ContratoMasajista();
        contratoMasajista.setVisible(true);
        dsktp_principal.add(contratoMasajista);
        dsktp_principal.moveToFront(contratoMasajista);
    }//GEN-LAST:event_jmitem_MasajistaContratoMouseClicked

    private void jmitem_TratamientoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_TratamientoListMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        ListadoTratamientos listadoTratamientos = new ListadoTratamientos();
        listadoTratamientos.setVisible(true);
        dsktp_principal.add(listadoTratamientos);
        dsktp_principal.moveToFront(listadoTratamientos);
    }//GEN-LAST:event_jmitem_TratamientoListMouseClicked

    private void jmitem_TratamientoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitem_TratamientoRegistroMouseClicked
        dsktp_principal.removeAll();
        dsktp_principal.repaint();
        RegistroTratamiento registoTratamiento = new RegistroTratamiento();
        registoTratamiento.setVisible(true);
        dsktp_principal.add(registoTratamiento);
        dsktp_principal.moveToFront(registoTratamiento);
    }//GEN-LAST:event_jmitem_TratamientoRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktp_principal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenu jmInstalaciones;
    private javax.swing.JMenu jmMasajistas;
    private javax.swing.JMenu jmSesiones;
    private javax.swing.JMenu jmTratamiento;
    private javax.swing.JMenuItem jmitem_Cliente;
    private javax.swing.JMenuItem jmitem_InstalacionesList;
    private javax.swing.JMenuItem jmitem_MasajistaContrato;
    private javax.swing.JMenuItem jmitem_MasajistaList;
    private javax.swing.JMenuItem jmitem_SesionNueva;
    private javax.swing.JMenuItem jmitem_TratamientoList;
    private javax.swing.JMenuItem jmitem_TratamientoRegistro;
    // End of variables declaration//GEN-END:variables
}
