/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Maxi
 */
public class JF_inicio extends javax.swing.JFrame {

    /**
     * Creates new form JF_inicio
     */
    public JF_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCliente = new javax.swing.JMenu();
        jmitem_Cliente = new javax.swing.JMenuItem();
        jmMasajistas = new javax.swing.JMenu();
        jmitem_MasajistaList = new javax.swing.JMenuItem();
        jmitem_MasajistaContrato = new javax.swing.JMenuItem();
        jmInstalaciones = new javax.swing.JMenu();
        jmitem_InstalacionesList = new javax.swing.JMenuItem();
        jmTratamiento = new javax.swing.JMenu();
        jmitem_TratamientoList = new javax.swing.JMenuItem();
        jmitem_TratamientoRegistro = new javax.swing.JMenuItem();
        jmSesiones = new javax.swing.JMenu();
        jmitem_SesionNueva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        jmCliente.setText("Cliente");

        jmitem_Cliente.setText("Registro");
        jmCliente.add(jmitem_Cliente);

        jMenuBar1.add(jmCliente);

        jmMasajistas.setText("Masajistas");

        jmitem_MasajistaList.setText("Listado");
        jmMasajistas.add(jmitem_MasajistaList);

        jmitem_MasajistaContrato.setText("Contratar");
        jmMasajistas.add(jmitem_MasajistaContrato);

        jMenuBar1.add(jmMasajistas);

        jmInstalaciones.setText("Intalaciones");

        jmitem_InstalacionesList.setText("Listado ");
        jmInstalaciones.add(jmitem_InstalacionesList);

        jMenuBar1.add(jmInstalaciones);

        jmTratamiento.setText("Tratamientos");

        jmitem_TratamientoList.setText("Listado");
        jmTratamiento.add(jmitem_TratamientoList);

        jmitem_TratamientoRegistro.setText("Registro ");
        jmTratamiento.add(jmitem_TratamientoRegistro);

        jMenuBar1.add(jmTratamiento);

        jmSesiones.setText("Sesiones");

        jmitem_SesionNueva.setText("Sacar Turno");
        jmSesiones.add(jmitem_SesionNueva);

        jMenuBar1.add(jmSesiones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenu jmInstalaciones;
    private javax.swing.JMenu jmMasajistas;
    private javax.swing.JMenu jmSesiones;
    private javax.swing.JMenu jmTratamiento;
    private javax.swing.JMenuItem jmitem_Cliente;
    private javax.swing.JMenuItem jmitem_InstalacionesList;
    private javax.swing.JMenuItem jmitem_MasajistaContrato;
    private javax.swing.JMenuItem jmitem_MasajistaList;
    private javax.swing.JMenuItem jmitem_SesionNueva;
    private javax.swing.JMenuItem jmitem_TratamientoList;
    private javax.swing.JMenuItem jmitem_TratamientoRegistro;
    // End of variables declaration//GEN-END:variables
}
