/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Masajista;

import modelo.Tratamiento;
import persistencia.Conexion;
import persistencia.MasajistaData;
import persistencia.TratamientoData;

/**
 *
 * @author Alan
 */
public class ListadoTratamientos extends javax.swing.JInternalFrame {

    
    private ArrayList<Tratamiento> listaT;
    private TratamientoData tratamientoData;
    
    private DefaultTableModel modeloTabla;
    
    Conexion con = new Conexion();
    
    
    public ListadoTratamientos() {
        
        
        initComponents();
        
        tratamientoData = new TratamientoData(con);
        listaT = (ArrayList<Tratamiento>)tratamientoData.listarTratamientos();
        
        
        modeloTabla = new DefaultTableModel();
        cargarTratamiento();
        cargarColumnasTablas();
        tratamientoTablaTipos();
        
    }

    private void cargarTratamiento(){
        
        
        
            
        jcb_listadoTratam.addItem("Facial");
        jcb_listadoTratam.addItem("Estetico");
        jcb_listadoTratam.addItem("Corporal");
        
            
            
        
        
       
    }
    
    
    private void cargarColumnasTablas(){
        
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Nombre");
        filaCabecera.add("Tipo");
        filaCabecera.add("Detalle");
        filaCabecera.add("Duracion");
        filaCabecera.add("Costo");
        for(Object it: filaCabecera){
            modeloTabla.addColumn(it);
        }
        tbl_tablaTratamientos.setModel(modeloTabla);
        
    }
    
    private void borrarFilaTabla(){
        
        int indice = modeloTabla.getRowCount() - 1;
        for(int i = indice; i >= 0 ; i-- ){
        
            modeloTabla.removeRow(i);
            
        
        }
         
    }
    
    private void tratamientoTablaTipos(){
    
        borrarFilaTabla();
        String seleccion = (String) jcb_listadoTratam.getSelectedItem();
        listaT = (ArrayList<Tratamiento>) tratamientoData.listarTratamientoTipo(seleccion);
        
        for(Tratamiento tratamiento: listaT){
            
            modeloTabla.addRow(new Object[]{
            
            tratamiento.getNombre(),
            tratamiento.getTipo(),
            tratamiento.getDetalle(),
            tratamiento.getDuracion(),
            tratamiento.getCosto()
            
            
            });
            
            
            
        }
        
        
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloListTratam = new javax.swing.JLabel();
        lbl_tratam = new javax.swing.JLabel();
        jcb_listadoTratam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaTratamientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        lbl_tituloListTratam.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lbl_tituloListTratam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloListTratam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloListTratam.setText("L I S T A D O   D E   T R A T A M I E N T O S");

        lbl_tratam.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lbl_tratam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tratam.setText("Tratamientos:");

        jcb_listadoTratam.setBackground(new java.awt.Color(204, 204, 204));
        jcb_listadoTratam.setForeground(new java.awt.Color(51, 51, 51));
        jcb_listadoTratam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_listadoTratamActionPerformed(evt);
            }
        });

        tbl_tablaTratamientos.setBackground(new java.awt.Color(204, 204, 204));
        tbl_tablaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablaTratamientos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("● ――――――――――――――――――――――――――――――――― ●");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_tituloListTratam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_tratam)
                                .addGap(32, 32, 32)
                                .addComponent(jcb_listadoTratam, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloListTratam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tratam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_listadoTratam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_listadoTratamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_listadoTratamActionPerformed
        tratamientoTablaTipos();
    }//GEN-LAST:event_jcb_listadoTratamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_listadoTratam;
    private javax.swing.JLabel lbl_tituloListTratam;
    private javax.swing.JLabel lbl_tratam;
    private javax.swing.JTable tbl_tablaTratamientos;
    // End of variables declaration//GEN-END:variables
}
